service: crypto-data # NOTE: update this with your service name
frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x
  stage: ${opt:stage, 'dev'}
  region: ${env:AWS_REGION}
  profile: sls-user
  memorySize: 512
  deploymentBucket:
    name: ${env:S3_BUCKET_SERVERLESS}

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  pull:
    handler: bin/crypto
    environment:
      AWS_REGION_PB: ${env:AWS_REGION_PB}
      S3_BUCKET_DATA_LAKE: ${env:S3_BUCKET_DATA_LAKE}
      CRYPTO_COMPARE_KEY: ${env:CRYPTO_COMPARE_KEY}
