service: crypto-data # NOTE: update this with your service name
frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x
  stage: ${opt:stage, 'dev'}
  region: ${env:AWS_REGION}
  profile: sls-user
  memorySize: 512
  deploymentBucket:
    name: ${env:S3_BUCKET_SERVERLESS}

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  hello:
    handler: bin/hello
    events:
      - http:
          path: hello
          method: get
  world:
    handler: bin/world
    events:
      - http:
          path: world
          method: get
